### ISSUE TITLE
Сохранение записей в работе с возражениями

### ISSUE THREAD

**Issue by Jaodi** [Jaodi/rrty#17]
>В работе с возражениями записи также не сохраняются при выходе, сохранилась только галочка, и то одна. Как я понимаю, не сохраняются записи и галочка при возражении ИЗМЕНИЛИСЬ ТРЕБОВАНИЯ/УСЛОВИЯ.

Сергей Есин

**Comment by SergeyEsin** [comment]
Что с этим вопросом? Мы работаем в СРМ, пытаемся актуализировать базу, но вносимые изменения в этот пункт, которые должны попадать в контакт-центр, туда не попадают!

**Comment by SergeyEsin** [comment]
Исправьте это первым делом, мы выполняем работу впустую.

**Comment by Jaodi** [comment]
Принятие возражения "изменились требования/условия" теперь работает правильно. Переход в к/ц так же функционирует

**Comment by SergeyEsin** [comment]
Сохраняется, но в КЦ не уходит.
Найдите в запросе на актуализацию этого клиента:
![image](https://cloud.githubusercontent.com/assets/13449266/8872181/c98dacb4-320b-11e5-81df-de462027a1f6.png)

**Comment by Jaodi** [comment]
Сегодняшние "изменились требования/условия" уже попадали в контакт-центр, но в форме актуализации не было сортировки по датам, потому их не получалось отыскать среди старых записей. Добавлена сортировка по датам в этой форме, теперь верхние в списке - самые свежие.
