### ISSUE TITLE
Поправки к письму из контакт-центра

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#18]
![-](https://cloud.githubusercontent.com/assets/13449266/8822912/c76426ea-3079-11e5-8202-7fbe9b16a344.jpg)

**Comment by Kasvin** [comment]
Коллеги, добрый день.

Почта, как вы возможно уже увидели, готова. Несколько примечаний:

1) Подпись будет такая, как указано в форме "Пользователи системы". Подпись не может браться из формы брокеров, поскольку отправиь почту может любой пользователь. Исправлено только имя Михаила Сидорова; остальных надо проверить и сделать как нужно. Вход туда только с большими правами.

2) Мы сейчас поставили округление цены до тысяч в соответствии с правилами округления. Если нужна другая дисциплина, то пожалуйста сообщите, какая именно.

3) Модифицировали форму отправки почты - теперь почту можно отправить только тогда, когда создано требование.
