### ISSUE TITLE
Пропадает текст в разговоре с потенциальным арендатором

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#19]
при нажатии галочек презентация получена и презентация просмотрена пропадает текст в окошке под этими галочками
![image](https://cloud.githubusercontent.com/assets/13449266/8823132/9b5ba382-307b-11e5-8c01-61e05f4b277a.png)

**Comment by Jaodi** [comment]
Текст комментариев теперь не теряется при нажатии любой из галочек или кнопки закончить разговор.
