### ISSUE TITLE
Не сохраняются данные о составе платежей при вводе помещения.

### ISSUE THREAD

**Issue by Jaodi** [Jaodi/rrty#2]
>У меня есть вопросы по работе в CRM системе. Информация в прикрепленном файле.

Татьяна Дорофеева.

![image 9](https://cloud.githubusercontent.com/assets/10849303/8775087/76207a5a-2eed-11e5-8e84-b415ee641b29.png)

**Comment by Jaodi** [comment]
Предлагается создавать LB_CONTRACT под аренду сразу при создании нового помещения, чтобы не заниматься его последующей вставкой в момент ввода цены. Так же решиться проблема сохранения галочек про состав платежей

**Comment by Kasvin** [comment]
Договора аренды создаются при создании помещения. Написана и пропущена программа, создающая такие договоры для всезх помещений. Протестировано.
