### ISSUE TITLE
Не появился объект в форме разговора с ПАПом

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#21]
Добавил в базу новое требование, подобралось 2 моих объекта (Зеленоградская, 18а и Алтуфьевское шоссе, 86), добавил их в план звонков. В итоге в плане звонков они оба есть, а в форме разговора с ПАПом - только Зеленоградская, 18а. Клиент - Артём.
![image](https://cloud.githubusercontent.com/assets/13449266/8828563/e7c35184-30a3-11e5-93c0-d662f281fc6e.png)
![image](https://cloud.githubusercontent.com/assets/13449266/8828574/f431c040-30a3-11e5-83e8-a77aed340910.png)

**Comment by SergeyEsin** [comment]
И дата контакта в форме разговора с ПАПом не отображается.

**Comment by Jaodi** [comment]
Проблема в том, что в форме создания требования не была нажата кнопка "оформить требование". В ней будет запрещено отсылать почту и отправлять в планы брокерам, пока не оформлено требование. 
Запись этих двух [Артему] звонков будут удалены. И клиента и требование придется завести заново.

**Comment by Jaodi** [comment]
Кнопку "оформить требования" нажимали, и клиент и требование созданы. Источник ошибки пока не исправлен.

**Comment by Jaodi** [comment]
Проблема была решена вместе с изменением типа добавляемого мероприятия из ввода/коррекции требований. Анкеты по каждому из объектов сейчас создадутся правильные
