### ISSUE TITLE
При поиске требования через листинг по номеру телефона подобралось одно требование, к нему подобрался один объект. Я точно знаю, что этот объект уже есть в плане звонков, а в этой форме это никак не отображается.

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#23]
![image](https://cloud.githubusercontent.com/assets/13449266/8848609/ac435702-3149-11e5-99a5-3aebd1a00fd2.png)

**Comment by SergeyEsin** [comment]
Объект должен же красным быть выделен.

**Comment by Jaodi** [comment]
Добавить в форму RT_0012 возможность видеть предложенные объекты

**Comment by Jaodi** [comment]
В форме предложенные объекты выделены цветом
