### ISSUE TITLE
Не отображается требование в плане звонков при отборе по объекту (в данном случае 3-я Парковая, 20)

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#24]
![image](https://cloud.githubusercontent.com/assets/13449266/8926991/55ff1c98-3525-11e5-8230-3ba7310f0be3.png)
![image](https://cloud.githubusercontent.com/assets/13449266/8927003/68b995b6-3525-11e5-946a-e27624677d15.png)

**Comment by Jaodi** [comment]
Статус помещения "Белые ночи" - реализовано. Из-за этого оно не показывается в плане звонков

**Comment by SergeyEsin** [comment]
А как мне другое помещение добавить из этого же объекта вместо "Белых ночей"?

**Comment by Jaodi** [comment]
Сейчас этого сделать из программы нельзя. В разовом случае, можно сделать изменения непосредственно в базе.
Вызвано это тем, что создание нескольких анкет по разным помещениям одного объекта сейчас запрещено. Это сделано как мера предотвращения большого количества анкет (когда в одном объекте похожие помещения и все подходят одной и той же заявке). Принятие каких-либо быстрых решений по этому вопросу затруднительно, потому что предполагает разработку общей логики поведения в таких ситуациях.
