### ISSUE TITLE
При звонке из СРМ почему-то получается, что я звоню сам себе, а не клиенту

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#25]
![image](https://cloud.githubusercontent.com/assets/13449266/8930216/ba52f2b4-3534-11e5-9a37-a7f97bc3eeae.png)

**Comment by Jaodi** [comment]
Надо "поднять трубку", вас соединит с клиентом. Сейчас это единственный способ взаимодействия с Ip телефонией.
