### ISSUE TITLE
В план звонков попали звонки из контакт-центра, Миша отправлял мне только 1-й и последний контакт из этого списка. Откуда взялись остальные?

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#27]
![image](https://cloud.githubusercontent.com/assets/13449266/8955462/9634b478-35f5-11e5-8f16-13b5ddb000d7.png)

**Comment by Jaodi** [comment]
Они были добавлены из формы контакт-центра брокером.

**Comment by SergeyEsin** [comment]
Мной что ли?

**Comment by Jaodi** [comment]
Записи добавлены в половину четвертого вчера из-под пользователя esf. Кажется никаких похожих действий в тестовом режиме никто вчера не делал. 
Ты себе их не добавлял?

**Comment by SergeyEsin** [comment]
Нет, я вчера в эту форму не заходил, подбор если и делал какой-то, то через листинг.

**Comment by Jaodi** [comment]
Форма листинга и формы контакт-центра под брокерскими пользователями теперь создают планы с пометкой "Звонок из поиска требований"
