### ISSUE TITLE
При поиске требования через листинг имя отображается одно имя, а когда "проваливаешься" в это требование двойным кликом - другое.

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#28]
![image](https://cloud.githubusercontent.com/assets/13449266/8984608/4f01aca0-36db-11e5-810e-dfb3dc822c66.png)
![image](https://cloud.githubusercontent.com/assets/13449266/8984613/59988954-36db-11e5-93e6-a42e02b0a670.png)

**Comment by Kasvin** [comment]
В поиске поставили отображение такого же  имени ПАПа
