### ISSUE TITLE
Добавил новое требование из листинга для объекта 3-я Парковая, но оно не появилось в плане звонков

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#30]
![image](https://cloud.githubusercontent.com/assets/13449266/8985877/08e53dfc-36e2-11e5-9f53-d1854f0041c8.png)
![image](https://cloud.githubusercontent.com/assets/13449266/8985881/0c3d2b18-36e2-11e5-97b1-c03174a6536d.png)

**Comment by SergeyEsin** [comment]
![image](https://cloud.githubusercontent.com/assets/13449266/8985916/3d33c1be-36e2-11e5-9208-51d214e55a35.png)

**Comment by Jaodi** [comment]
Этот звонок восстановлен. 
Проблема добавления так же решена. (по умолчанию листинг добавлял звонок на первое помещение в объекте, которое на третьей парковой реализовано)
