### ISSUE TITLE
В выпадающем списке  - неработающие брокеры, нужно поправить или дать инструкцию как это сделать самостоятельно

### ISSUE THREAD

**Issue by RRTY** [Jaodi/rrty#31]
![image](https://cloud.githubusercontent.com/assets/13433611/8988075/d7659550-36ec-11e5-852b-cb5e990f544f.png)

**Comment by Kasvin** [comment]
Уволенные брокеры в списке больше не показываются.

Для увольнения агентов нужно зайти в форму Ядро/Справочники персонала/Брокеры и в поле "статус" установить "Уволен".

**Comment by Kasvin** [comment]
Новая форма будет установлена, как только все из нее выйдут.
