### ISSUE TITLE
Угроза - плагин вскоре не будет поддерживаться.

### ISSUE THREAD

**Issue by RRTY** [Jaodi/rrty#32]
![image](https://cloud.githubusercontent.com/assets/13433611/8991993/b8df0720-3704-11e5-864f-3b21d6e0aa27.png)

**Comment by Jaodi** [comment]
chrome объявил о приостановке поддержки java плагинов некоторое время назад. Сейчас это предупреждение можно игнорировать. Нашем решением в случае невозможности запуска из новой версии хрома будет либо "замораживание" некоторой рабочей версии этого браузера, либо какой-то другой браузер.
