### ISSUE TITLE
Отправил презентацию и назначил дату след. звонка на 03.08.2015 по Волоколамскому шоссе, 14. В плане звонков всё правильно, а в форме RT-08 запись попала в 3-ю Парковую, 20, а след. звонок в Волоколамское шоссе, 14.

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#33]
![image](https://cloud.githubusercontent.com/assets/13449266/9004788/c51868ba-3781-11e5-8f08-a34e9669c37e.png)
![image](https://cloud.githubusercontent.com/assets/13449266/9004798/d523c8da-3781-11e5-8558-4d2ad07f3b42.png)
![image](https://cloud.githubusercontent.com/assets/13449266/9004812/e50efda0-3781-11e5-9da5-6f8e442c8bca.png)

**Comment by Jaodi** [comment]
В этих анкетах все поставили на место.
Такой эффект получается, если переключиться между анкетами не бегунком или нажатием в название, а сразу нажав в кнопку "Назначить мероприятие".
Чтобы не дать повторения ошибки нужно установить форму с исправлениями.
