### ISSUE TITLE
Почему, когда открываешь форму RT-08, сначала видишь последние объекты в списке, а не первые?

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#34]
![image](https://cloud.githubusercontent.com/assets/13449266/9004891/990b254a-3782-11e5-99bb-4c91bd915611.png)
![image](https://cloud.githubusercontent.com/assets/13449266/9004902/a3a2b0e0-3782-11e5-980f-d1167fead94e.png)

**Comment by Jaodi** [comment]
Можно сделать наоборот, что, как кажется, ничем не лучше. 
Здесь предполагалась фокусировка при входе на анкету, по которой зашли в форму. Поскольку сейчас будет приниматься решение, о том, чтобы объединить записи в плане звонков по разным объектам в одну дату, этого сделано не было. 
Этот вопрос можно разрешить только совместно с #20

**Comment by SergeyEsin** [comment]
Так я заходил по Волоколамскому шоссе, а фокусировка на 3-й Парковой, разговор по которой был давно.

**Comment by Jaodi** [comment]
>Здесь предполагалась фокусировка при входе на анкету, по которой зашли в форму. Поскольку сейчас будет приниматься решение, о том, чтобы объединить записи в плане звонков по разным объектам в одну дату, **этого сделано не было**. 

Это станет неактуальным сразу по принятию решения по новому виду плана звонков. В силу того, что изменение потребует некоторых временных затрат, предлагается отложить до обсуждения.
