### ISSUE TITLE
При нажатии на состояние (историю событий клиента) правой кнопкой мыши выдаёт ошибку и записи, которые были записаны, появляются по очереди после нажатия на "ОК", а не одновременно все записи в хронологическом порядке.

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#35]
![image](https://cloud.githubusercontent.com/assets/13449266/9035862/976330b6-39e4-11e5-920a-d9e34800450d.png)
![image](https://cloud.githubusercontent.com/assets/13449266/9035874/a4386ea0-39e4-11e5-844c-f7ab3056c395.png)
![image](https://cloud.githubusercontent.com/assets/13449266/9035880/afc2847c-39e4-11e5-8729-8b3d30609dee.png)

**Comment by Kasvin** [comment]
Сообщение на экране означает "Вы не можете здесь создать запись". Стандартно такое сообщение возникает в следующем случае: пусть есть просмотровый блок, т.е. блок записей, которые отображают состояние базы и только. Добавлять записи в таких блоках мы не разрешаем, обычно блокируем клавишу "+". Но если в этом блоке есть пустые строчки, и в них ткнуть мышкой, то программа думает, что Вы собираетесь создать запись и сообщает Вам, что тут этого сделать нельзя. Сообщение информационное и совершенно неопасное. Сегодня посмотрим, стоит ли установить дополнительную защиту от этого сообщения, и как это лучше сделать. Стандартно его надо просто игнорировать.

**Comment by SergeyEsin** [comment]
Так в пустые строчки я мышкой не нажимал, я нажимаю правой кнопкой на требование...

**Comment by Kasvin** [comment]
Понял, спасибо, сегодня проверим. Значит, переход на такую запись - следствие. Проверим обязательно.

**Comment by Jaodi** [comment]
Установлена новая форма. Несколько записей в истории теперь отображаются правильно.
