### ISSUE TITLE
Изменить ширину столбцов

### ISSUE THREAD

**Issue by SergeyEsin** [Jaodi/rrty#40]
![image](https://cloud.githubusercontent.com/assets/13449266/9131432/25a87914-3cf4-11e5-9fbf-3e7c121335a0.png)
Необходимо увеличить размеры столбцов тел.1, тел.2, эл. почта, чтобы была видна вся содержащаяся в них информация. Столбец контактные лица нужно уменьшить раза в 3.

**Comment by Kasvin** [comment]
Посмотрите, думаю, ок.
