### ISSUE TITLE
Кнопки для фильтрации блока окружения слишком маленькие ( в них не умещается текст )

### ISSUE THREAD

**Issue by Jaodi** [Jaodi/rrty#8]
![image 1](https://cloud.githubusercontent.com/assets/10849303/8806404/3e0f7146-2fdf-11e5-9464-c793b6a1bfc9.png)

**Comment by Jaodi** [comment]
Курсор на новую строку не ставится по причине незаполненности предыдущей. Запись в этом блоке считается введенной только после заполнения всех обязательных полей.
Так же следует обратиться к функции автоматической загрузки окружения перед началом его ручного ввода/изменения.

**Comment by Jaodi** [comment]
Кнопки увеличены

**Comment by SergeyEsin** [comment]
Ничего не изменилось, текст не умещается!
![image](https://cloud.githubusercontent.com/assets/13449266/8951283/bc32d86a-35d4-11e5-92aa-4b7cdcd8a265.png)

**Comment by Jaodi** [comment]
Ошиблись с версией формы. Размер кнопок теперь правильный
